### ISSUE TITLE
Reword "Is [:nick] stupid or just asking too many questions?"

### ISSUE THREAD

**Issue by rootkea** [PISG/pisg#12]
Hello!

Often in an IRC channel it's the newbie who asks the most number of questions. Calling someone "stupid" just for asking most questions quite doesn't sound welcoming (or funny for that matter).

Please reword it. May be we can go for a positive adjective like "curious"?

Thanks!

**Comment by p0358** [comment]
Well, "stupid" is just one possibility. If they're only a newbie, then perhaps they're "just asking too many questions". Thus I see nothing wrong

**Comment by rootkea** [comment]
> Well, "stupid" is just one possibility.

Sure. "curious" is another possibility. There might be other possibilities which we may not be aware of like any other event in life. The question is why to choose the negative possibility? Does it make the project welcoming/better? Especially when there are positive adjectives to replace "stupid".

**Comment by DooubleTap** [comment]
I will edit the code. 
-update: https://github.com/PISG/pisg/commit/c0d38ca231340e154d81074d74e945d4b69b5af0

**Comment by rootkea** [comment]
I see the commit and I don't see any change in negative tone (the core issue).

From the condescending commit message clearly I wasted my time. Anyways, if you think it makes the project welcoming/better then good luck.

(Thankfully, I have seen `pisg` used by only one IRC channel I'm (was) part of. #dgplug)

/end
