### ISSUE TITLE
[RFC] Remove gender

### ISSUE THREAD

**Issue by LordAro** [PISG/pisg#7]
The gender/sex stuff is a bit odd.

You're on the internet, no one cares about your gender and frankly it's a bit weird that you'd make a list recording it.

The other point is that the "he/she" for unknown cases (which is almost all of them) is rather wonky language and doesn't read very well.

I'd much prefer "they" in all cases.

**Comment by DooubleTap** [comment]
do you need a safe place to cry about your feelings too?  

please, go away with this feminist bullshit.

**Comment by LordAro** [comment]
Oh please, don't be so up yourself. My only concern is that the wording of "he/she" is very awkward, and is much more easily replaced with "they"

**Comment by jlu5** [comment]
_sigh_

Two years later and this isn't an isolated request anymore.

@SebLemery Seeing that PISG core already supports translating genders, would you consider accepting this as a separate language pack?

**Comment by DooubleTap** [comment]
> _sigh_
> 
> Two years later and this isn't an isolated request anymore.
> 
> @SebLemery Seeing that PISG core already supports translating genders, would you consider accepting this as a separate language pack?

fork your own. This stays. you can either be NONE, BOT, FEMALE, MALE. Nothing else. if you want more, feel free to do it on your own fork, but this is not something i will do. You're born a woman or a man, it's fun to have stats in blue or pink for some users. 

Sorry, not sorry.

**Comment by jlu5** [comment]
Oh, I'm not talking about removing the sex= config options, just having he/she => they, his/her => their as a custom language option

**Comment by LordAro** [comment]
Oh dear.

If you'll get off your high horse for a minute, you'll realise there's another option you've forgotten - "UNKNOWN".

On the internet, being "unknown" is an awful lot more common than you might think, rather than actually advertising yourself. Having "he/she" scattered around the output everywhere is just awkward to read, when "they" works just fine. You could even have it for bots, if you're really opposed to "a third gender".

I still think recording it is fairly pointless, but if you must keep it, no one here is suggesting any "feminist bullshit" like adding custom pronouns, just a "gender neutral" option

But given the only contribution you've made to this in the last 2 years is to add yourself to the credits, I think we're probably not going to make any progress on this

**Comment by jlu5** [comment]
I've opened #11 anyways.

**Comment by Ferrisx4** [comment]
I also support the idea of using "they" for when `sex=` isn't specified - I provide stats for a number of channels and I am aware of less than 5% of the genders which means he/she is littered through the stats pages. It's pretty awkward and clumsy to read.

**Comment by DooubleTap** [comment]
i am sorry but i do not want to be part of this they/them thing. Its Male, female, none or bot, only. there is 2 sexes on this planet, bots and people who dont want to say. nothing else is going to be supported here.

**Comment by jesopo** [comment]
using "they" as an uncertain singular pronoun has been a grammatical reality for a very long time. you don't need to compromise on your very cool very normal political beliefs to make a change to make your app less grammatically clumsy
