### ISSUE TITLE
Multiple log formats for one channel

### ISSUE THREAD

**Issue by p0358** [PISG/pisg#8]
I think a possibility of combining multiple log formats within a single channel would be great, in case you change the log format, but have a bunch of logs in the previous one.

**Comment by DooubleTap** [comment]
you should consider merging them together.

**Comment by p0358** [comment]
@SebLemery Do you have any ideas on how could that be done? Because I have an idea for the functionality proposed, I'm just not too good in Perl. There could be log groups in config, which could look like this:
```
    <loggroup="1">
     Logfile = "log.txt"
     Format = "xchat"
    </loggroup>
    
    <loggroup="1">
     LogDir = "dir"
     Format = "energymech"
    </loggroup>

    <channel="#test">
     Loggroup = "1"
     Format = "multi"
    </channel>
```
